site_name: Reinforcement Learning
# 
site_author: RP
# 
theme: 
    name: readthedocs #mkdocs #
    user_color_mode_toggle: true
    #nav_style: dark
#
nav:
    - index.md
    - simulations_package.md
    - bandits_package.md
#
plugins:
    - search
    - mkdocstrings:
        default_handler: python
        handlers:
            python:
                options:
                    show_source: false
                    show_root_toc_entry: false
                    docstring_style: numpy                    
                    parameter_headings: true
                    separate_signature: true
                    show_signature_annotations: true
                    signature_crossrefs: true                    