on:
  push:
    branches:
    - main
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - name: checkes
      run: |
          make format
          make lint
          
